config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # Change this later
  get "e/:funid", to: "events#join", as: :short_join_event
  get "e", to: "events#join", as: :pin_join_event # GET e?
  get "join", to: "pages#join"

  resources :events, only: %i[new create show] do
    resource :chosen_date, only: %i[show]
    get "/chosen_date/create", to: "chosen_dates#create", as: :chosen_date_create

    resources :attendees, only: [:create]
    get "join", on: :member

    resources :date_votes, only: %i[new create]
  end

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_features.html.erb
<div class="container px-4 " id="custom-cards">
  <h2 class="pb-2 border-bottom fw-bold text-white text-center display-5 mt-2">How it Works</h2>
  <h4 class="text-center mt-5">Choosing the date  for a special ocassion is now easier with the help of <strong>Akord</strong> </h4>

  <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
    <div class="col">
      <div class="card card-cover h-100 overflow-hidden text-white rounded-5 shadow-lg text-center blurr-filter">
        <div class="d-flex flex-column h-100 p-2 pb-3 text-white text-shadow-1">
          <h2 class="pt-5  mb-4 display-4 lh-1 fw-bold text-withe">Create</h2>
          <div class="img-fluid mb-2 ">
            <%= image_tag "create.png", class:"img-index" %>
          </div>
          <h4>Create your event and describe its details</h4>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card card-cover h-100 overflow-hidden text-white rounded-5 shadow-lg text-center blurr-filter">
        <div class="d-flex flex-column h-100 p-2 pb-3 text-white text-shadow-1">
          <h2 class="pt-5  mb-4 display-4 lh-1 fw-bold text-withe">Vote</h2>
          <div class="img-fluid mb-2 ">
            <%= image_tag "Invite.png", class:"img-index" %>
          </div>
          <h4>Share with your guests and vote for their favorite day</h4>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card card-cover h-100 overflow-hidden text-white rounded-5 shadow-lg text-center blurr-filter">
        <div class="d-flex flex-column h-100 p-2 pb-3 text-shadow-1">
          <h2 class="pt-5 mb-4 display-5 lh-1 fw-bold text-withe">Save the date</h2>
          <div class="img-fluid mb-2 ">
            <%= image_tag "selection.png", class:"img-index" %>
          </div>
          <h4>Select the day with the most votes</h4>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid d-flex justify-content-center">
    <% if user_signed_in? %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-link" %>
    <% else %>
        <%= link_to "Login", new_user_session_path, class: "btn btn-link" %>
    <% end %>
  </div>
</div>

app/views/shared/_hero.html.erb
<%= image_tag "akord1.png", class: "img-fluid mt-4 mb-3", style: "max-height: 120px" %>
<h1 class="display-4 fw-bold mt-4 mb-4 text-white">Simply get TOGETHER</h1>
<div class="col-lg-6 mx-auto">
  <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-4 mt-5">
    <%= link_to 'Create event', new_event_path, class: "btn btn-primary btn-lg px-4 me-sm-3 border-radius text-white fw-bold"%>
    <%= link_to 'Vote for event', join_path, class: "btn btn-secondary btn-lg px-4 border-radius text-white fw-bold"%>
  </div>
</div>
<div class="overflow-hidden" style="max-height: 40vh;">
  <div class="container px-5">
    <%= image_tag "calendar.png", class: "img-fluid rounded-3 shadow-lg mb-5 blurr-filter", alt: "calendar", width: "700", height: "500", loading:"lazy" %>
  </div>
</div>