config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # Change this later
  get "e/:funid", to: "events#join", as: :short_join_event
  get "e", to: "events#join", as: :pin_join_event # GET e?
  get "join", to: "pages#join"

  resources :events, only: %i[new create show] do
    resource :chosen_date, only: %i[show]
    get "/chosen_date/create", to: "chosen_dates#create", as: :chosen_date_create

    resources :attendees, only: [:create]
    get "join", on: :member

    resources :date_votes, only: %i[new create]
  end

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  include Hashid::Rails

  belongs_to :user
  has_many :votes
  has_many :attendees, -> { distinct }, through: :votes

  before_create :set_funid_pin

  validates :title, presence: true

  validate :votable_date_before_today

  def event_dates
    votable_dates_strings.map { |date_string| Event::Date.new(date_string, self) }
  end

  def dates_rate
    votes.group(:date).sum(:rate)
  end

  def closed?
    chosen_date.present?
  end

  def chosen_date
    super.blank? ? nil : Event::Date.new(super.to_s, self)
  end

  # Might help with flatpick values if they are JSON
  # "2020-10-10, 2020-10-11" => ["2020-10-10", "2020-10-11"]
  def votable_dates_strings=(value)
    value = value.split(", ") if value.is_a? String
    super(value)
  end

  def votable_dates
    votable_dates_strings.map { |ds| ::Date.parse(ds) }
  end

  private

  def set_funid_pin
    self.funid = generate_fun_id
  end

  def generate_fun_id
    nouns = %w[goose pancake pie gorilla memory shirt pickle fruit beast house]
    adjectives = %w[pretty funky smelly dirty silly tiny kind huge lovely delighful sweet]
    loop do
      funid = "#{adjectives.sample}-#{nouns.sample}"
      break funid unless Event.where(funid: funid).exists?
    end
  end

  def votable_date_before_today
    errors.add(:votable_dates_strings, "Cannot select past dates") if any_past_dates?
  end

  def any_past_dates?
    votable_dates.any? { |date| date < ::Date.current }
  end
end

app/models/event/date.rb
# Presenter for Event Date
class Event::Date
  attr_reader :value, :event

  def initialize(date_string, event)
    @value = Date.parse(date_string)
    @event = event
  end

  def ==(other)
    (value == other.value) && (event == other.event)
  end

  def chosen?
    event.chosen_date == self
  end

  # Example of things the view might need
  def short_string
    value.strftime("%a, %b %d")
  end

  def year
    value.strftime("%Y")
  end

  def week_day
    value.strftime("%a")
  end

  def month
    value.strftime("%b")
  end

  def month_number
    value.strftime("%-m")
  end

  def day
    value.strftime("%d")
  end

  def votes
    event.votes.where(date: value)
  end

  def rate
    votes.sum(:rate)
  end

  def total_votes
    votes.count
  end

  def yes_count
    votes.where(rate: :yes).count
  end

  def no_count
    votes.where(rate: :no).count
  end

  def maybe_count
    votes.where(rate: :maybe).count
  end

  def progress_bar_value
    total_votes.zero? ? 0 : (yes_count * 100) / total_votes
  end

  def limt_three_voters
    i = 0
    while i < 3
      event_date.votes[i].attendee.name
      i += 1
    end
  end

  def to_partial_path
    "event_date"
  end

  def outlook_url
    calendar_url_builder.outlook_com_url
  end

  def google_url
    calendar_url_builder.google_url
  end

  private

  def calendar_url_builder
    @calendar_url_builder ||= AddToCalendar::URLs.new(
      start_datetime: Time.new(year, month_number, day),
      end_datetime: Time.new(year, month_number, day, 23, 59, 59, 0), # required
      title: event.title, # required
      timezone: 'America/Mexico_City', # required
      url: "https://www.akord.me/events/#{event.hashid}",
      description: "Host: #{event.user.attendee.name}🥳\n#{event.description}",
      add_url_to_description: true # defaults to true
    )
  end
end

app/models/event/date_votes.rb
class Event::DateVotes
  include ActiveModel::Model
  attr_accessor :attendee, :event

  def voted?
    @voted ||= attendee.votes.where(event: event).exists?
  end

  def votes
    @votes ||= voted? ? attendee.votes.where(event: event) : build_votes
  end

  def votes_attributes=(value)
    @votes_attributes = value
  end

  def submit
    attributes = @votes_attributes.transform_values do |value|
      value.merge(attendee: attendee, event: event, rate: value[:rate].to_i)
    end
    Vote.create!(attributes.values)
  end

  private

  def build_votes
    event.votable_dates_strings.map do |date_string|
      Vote.new(event: event, attendee: attendee, date: date_string)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show join]

  def show
    @event = Event.find(params[:id])
  end

  # GET  /e/:funid
  # GET  /e?funid=
  def join
    @event = Event.find_by_funid!(params[:funid])
    redirect_to new_event_date_vote_path(@event) if current_attendee.present?

    @attendee = Attendee.new
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to event_path(@event.hashid), notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :votable_dates_strings)
  end
end

app/views/events/_event_date.html.erb
<% if current_user&.owns?(@event) && @event.closed? == false %>
  <%= link_to "Choose this date", event_chosen_date_create_path(event_date.event, date_string: event_date.value), data: { controller: "swal", swal_short_string_value: event_date.short_string, action: "swal#alert" }, class: "text-secondary" %>
<% end %>
<div data-date=<%= event_date.value %> class="mb-2">
  <div class="d-flex blurr-filter px-3 <%= event_date.chosen? ? "border border-3 border-secondary" : "" %>">
    <div class="pe-3 align-items-center d-flex justify-content-between ">
      <p class="day_date mb-0 <%= event_date.chosen? ? "text-secondary" : "" %>"><strong><%= event_date.day %></strong></p>
      <div class="ms-1">
        <h5 class="mb-0 <%= event_date.chosen? ? "text-secondary" : "" %>"><%= event_date.month %></h5>
        <p class="mb-0 small text-muted"><%= event_date.week_day %></p>
      </div>
    </div>
    <div class="flex-grow-1 pt-3">
      <div class="progress mb-1">
        <div class="progress-bar bg-secondary"
            style="width: <%= event_date.progress_bar_value %>% "
            aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"> <%# box-shadow:-1px 10px 10px rgba(91, 192, 222, 0.7); %>
        </div>
      </div>
      <div class="d-flex justify-content-between mb-1 small">
        <div class="text-black"><span class="yes-display"><%= event_date.yes_count %></span> yes</div>
        <div class="text-black"><span class="maybe-display"><%= event_date.maybe_count %></span> maybe</div>
        <div class="text-black"><span class="no-display"><%= event_date.no_count %></span> no</div>
      </div>
    </div>
  </div>
</div>

app/views/events/_invitation_links.html.erb
<div class="card w-100  mt-2 blurr-filter mb-3">
  <div class="card-body mb-0 text-center">
      <div class="border-radius bg-white d-inline-block p-3 mb-3">
        <%= event_qr_code(@event).svg %>
      </div>
      <div class="d-flex justify-content-center" data-controller="clipboard" data-clipboard-feedback-text-value="Copied!">
        <button class="btn btn-secondary rounded" data-action="click->clipboard#copy"><i class="fas fa-link"></i> Copy</button>
        <input class="blurr-filter border-0 rounded " value="<%= short_join_event_url(@event.funid) %>" data-clipboard-target="input" type="text" readonly>
      </div>
      <% if current_user %>
        <%= link_to 'vote', new_event_date_vote_path(@event), class: "text-white" %>
      <% end %>
  </div>
</div>

app/views/events/join.html.erb
<div class="wrapper">
  <div class="container min-vh-100 d-flex flex-column justify-content-center align-items-center">
    <div class= col-sm-6>
      <%= image_tag "akord.png", height: 200, class: "img-fluid" %>
      <div class="justify-content-center">
        <div class="card form-login blurr-filter m-1 text-center">
          <h3>
            Joining <%= @event.title %>
          </h3>
            <div class="container d-flex justify-content-center m-1">
              <%= simple_form_for [@event, @attendee] do |f| %>
                <%= f.input :name, label: "Who are you?", placeholder:"E.g.: Uncle John", input_html: { class: "blurr-filter border-0" }, error: "Hmm, seems that a name is missing here🤔" %>
                <%= f.button :submit, value:"Join", class:"button-radius btn btn-primary border-radius fw-bold text-white w-100 ms-0" %>
              <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="wrapper">
  <div class="container min-vh-100 d-flex justify-content-center mb-3">
    <div class="d-flex flex-column">
      <div class="card w-100  mt-4 blurr-filter">
        <div class="card-body">
          <h2 class="card-title fw-bold text-white text-center">Let's create an event!</h2>
        </div>
      </div>
      <div class="card w-100 mt-3 blurr-filter">
        <div class="card-body text-primary">
          <%= simple_form_for @event do |f| %>
            <div class="form-inputs text-white">
              <%= f.input :title, placeholder:"E.g.: Pizza Day!", input_html: { class: "border-radius blurr-filter border-0" }, error: 'Your event needs a title😯', error_html:{ class: "text-white" } %>
              <%= f.input :description, input_html: { class: "border-radius blurr-filter border-0" } %>
              <%= f.input :votable_dates_strings, label: "Choose possible dates", as: :string, input_html: { data: { controller: "pick-days" } }, wrapper_html: { class: "flatpickr-calendar-custom" } %>
            </div>
            <div class="form-actions d-flex justify-content-end">
              <%= link_to "Cancel", root_path, class:"btn btn-secondary border-radius text-white fw-bold  pt-2" %>
              <%= f.button :submit, class:"btn btn-primary border-radius text-white fw-bold pt-2 ms-3" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<% content_for :meta_title, "#{DEFAULT_META["meta_product_name"]} on #{@event.title}" %>
<% content_for :meta_description, @event.description %>

<div class="wrapper" data-controller="event-status-subscription votes-subscription" data-event-status-subscription-event-id-value="<%= @event.hashid %>" data-votes-subscription-event-id-value="<%= @event.hashid %>">
  <div class="min-vh-100 row justify-content-center mx-0 ">
    <div class="col-xs-12 col-sm-8 col-sm-offset-4 col-md-6 col-lg-4">
      <div class="card w-100  mt-4 blurr-filter">
        <div class="card-body mb-0 text-center py-2">
          <p class="text-white small mb-0">
            <i class="fas fa-user-shield"></i>
            <%= @event.user.attendee.name %>
          </p>
          <h1 class="card-title fw-bold text-info mb-0"><%= @event.title %></strong></h1>
          <p class="text-white small mb-0"><%= @event.description %></p>
        </div>
      </div>
      <div data-event-status-subscription-target="info">
        <% if @event.closed? %>
          <%= render "chosen_dates/modal", event: @event %>
        <% else %>
          <%= render "invitation_links" %>
        <%end%>
      </div>
      <div class="d-flex justify-content-between align-items-end mb-2" >
        <h2 class="text-info mt-2 mb-0"><strong>Results</strong></h2>
        <button class="d-inline-flex align-items-center btn btn-light badge"  data-bs-toggle="tooltip" data-bs-placement="top" title="<%= @event.attendees.pluck(:name).to_sentence %>">
          <span><i class="fas text-secondary fa-users"></i></span>&nbsp;<span class="badge btn-secondary total-display" data-votes-subscription-target="totalDisplay"><%= @event.attendees.count %></span>
        </button>
      </div>
      <div class="dates" data-votes-subscription-target="dates" data-event-status-subscription-target="dates">
        <%= render @event.event_dates %>
      </div>
    </div>
  </div>
</div>