config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # Change this later
  get "e/:funid", to: "events#join", as: :short_join_event
  get "e", to: "events#join", as: :pin_join_event # GET e?
  get "join", to: "pages#join"

  resources :events, only: %i[new create show] do
    resource :chosen_date, only: %i[show]
    get "/chosen_date/create", to: "chosen_dates#create", as: :chosen_date_create

    resources :attendees, only: [:create]
    get "join", on: :member

    resources :date_votes, only: %i[new create]
  end

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event/date_votes.rb
class Event::DateVotes
  include ActiveModel::Model
  attr_accessor :attendee, :event

  def voted?
    @voted ||= attendee.votes.where(event: event).exists?
  end

  def votes
    @votes ||= voted? ? attendee.votes.where(event: event) : build_votes
  end

  def votes_attributes=(value)
    @votes_attributes = value
  end

  def submit
    attributes = @votes_attributes.transform_values do |value|
      value.merge(attendee: attendee, event: event, rate: value[:rate].to_i)
    end
    Vote.create!(attributes.values)
  end

  private

  def build_votes
    event.votable_dates_strings.map do |date_string|
      Vote.new(event: event, attendee: attendee, date: date_string)
    end
  end
end

app/controllers/date_votes_controller.rb
class DateVotesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new create]
  def new
    event = Event.find(params[:event_id])
    attendee = current_attendee
    @date_votes = Event::DateVotes.new(attendee: attendee, event: event)

    redirect_to join_event_path(event.hashid) unless attendee.present?
    redirect_to event, alert: "You already voted!" if @date_votes.voted?
  end

  def create
    @event = Event.find(params[:event_id])
    @attendee = current_attendee
    @date_votes = Event::DateVotes.new(date_votes_params)
    if @date_votes.submit
      VotesChannel.broadcast_to(
        @event,
        @date_votes.votes.as_json(only: [:date, :rate])
      )
      redirect_to event_path(@event.hashid), notice: 'Your vote is in, Thanks!'
    else
      render :new
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def date_votes_params
    params.require(:event_date_votes).permit(votes_attributes: [:rate, :date]).merge(event: @event, attendee: @attendee)
  end
end

app/views/date_votes/new.html.erb
<div class="wrapper">
  <div class="overflow-hidden">
    <div class="container pt-5">
      <div class="card blurr-filter p-3 ">
        <h4  class="fw-bold text-white">Hey <%= current_attendee.name.capitalize %>! you are invited to <%= @date_votes.event.title.capitalize %> </h4>
        <p class="text-white"><%= @date_votes.event.description %></p>
        <h4 class="text-white">Let's <b>Akord</b> on a date for this event</h4>
      </div>
      <div class="d-flex flex-column m-5 mt-2">
        <%= simple_form_for @date_votes, url: event_date_votes_path do |f| %>
          <% first = true %>
          <%= f.simple_fields_for :votes do |fv| %>
            <%= fv.input :date, as: :hidden %>
            <div style="width: calc(100% - 10px)" class="<%= first ? 'jiggle' : '' %> voting-card effect-3d box-shadow m-auto position-relative swipe-maybe p-3 mb-3"  data-controller="swipe-radio">
                <div class="context-clue d-flex align-items-start">
                  <% if first %>
                    <p><strong>Swipe Me!<strong></p>
                  <% else %>
                    <%= icon "fa", "caret-left" %>
                    <i class="far fa-hand-paper"></i>
                    <%= icon "fa", "caret-right" %>
                  <% end %>
                  <% first = false %>
                </div>
              <div class="d-flex align-items-center">
                <%= fv.input :rate, as: :hidden, input_html: { data: { swipe_radio_target: :input } } %>
                <div class="p-2 align-items-center d-flex justify-content-between">
                  <p class="day_date mb-0"><strong><%= fv.object.event_date.day %></strong></p>
                  <div>
                    <h5 class="mb-0"><%= fv.object.event_date.month %></h5>
                    <p class="mb-0 small text-muted"><%= fv.object.event_date.week_day %></p>
                  </div>
                </div>
                <div class="icons" data-swipe-radio-target="icons">
                  <span class="thumbs" data-swipe-radio-target="maybe"><%= image_tag "maybe_icon.png", alt: "maybe", width: 40, height: 40 %></span>
                  <span class="thumbs d-none" data-swipe-radio-target="thumbsup"><i class="fa-solid fa-2x fa-thumbs-up"></i></span>
                  <span class="thumbs d-none" data-swipe-radio-target="thumbsdown"><i class="fa-solid fa-2x fa-thumbs-down"></i></span>
                </div>
              </div>
            </div>
          <% end %>
          <%= f.button :submit, class:"voting-button btn btn-primary text-white border-radius fw-bold", value: "VOTE !" %>
        <% end %>
      </div>
    </div>
  </div>
</div>