config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # Change this later
  get "e/:funid", to: "events#join", as: :short_join_event
  get "e", to: "events#join", as: :pin_join_event # GET e?
  get "join", to: "pages#join"

  resources :events, only: %i[new create show] do
    resource :chosen_date, only: %i[show]
    get "/chosen_date/create", to: "chosen_dates#create", as: :chosen_date_create

    resources :attendees, only: [:create]
    get "join", on: :member

    resources :date_votes, only: %i[new create]
  end

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/chosen_dates_controller.rb
class ChosenDatesController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @event.update(chosen_date: params[:date_string])

    EventStatusChannel.broadcast_to(
      @event,
      {
        dates: render_to_string(partial: "events/event_date", collection: @event.event_dates),
        info: render_to_string(partial: "chosen_dates/modal", locals: { event: @event }),
        alertWindow: render_to_string(partial: "chosen_dates/alert_window", locals: { event: @event })
      }
    )
    redirect_to event_chosen_date_path(@event)
  end

  def show
    @event = Event.find(params[:event_id])
  end
end

app/views/chosen_dates/_alert_window.html.erb
<p class=" mb-1"><strong><%= event.title.capitalize %></strong> will be on:</p>
<div class= "mb-1">
  <div class="d-inline-flex flex-column m-1 rounded overflow-hidden">
    <div class="px-4 py-1 h3  text-info bg-secondary mb-0 "><%= event.chosen_date.month%></div>
    <div class="px-4 py-1 bg-info chosen-day mb-0 fw-bold"><%=event.chosen_date.day%></div>
    <div class=" bg-dark text-info mb-0"><%=event.chosen_date.week_day%></div>
  </div>
</div>

app/views/chosen_dates/_modal.html.erb
<div class="justify-content-center w-100">
  <div class="card py-2 px-1 blurr-filter mt-2 text-center">
    <h3 class="fw-bold">All votes are in!</h3>
    <p class=" mb-1"><strong><%= @event.title.capitalize %></strong> will be on:</p>
    <div class= "mb-1">
      <div class="d-inline-flex flex-column m-1 rounded overflow-hidden">
        <div class="px-4 py-1 h3  text-info bg-secondary mb-0 "><%= @event.chosen_date.month%></div>
        <div class="px-4 py-1 bg-info chosen-day mb-0 fw-bold"><%=@event.chosen_date.day%></div>
        <div class=" bg-dark text-info mb-0"><%=@event.chosen_date.week_day%></div>
      </div>
    </div>
    <p class=" mb-1">You can add it to you calendar!</p>
  </div>
  <div class="d-flex justify-content-evenly mt-3">
    <a class="btn p-2 badge btn-secondary border-radius border-0 blurr-filter" href="<%= @event.chosen_date.google_url %>"><strong>Google Calendar</strong>
    <span><%= image_tag "google.png", height: 20, width: 20, class: "img-fluid" %></span></a>
    <a class="btn p-2 badge btn-secondary border-radius border-0 blurr-filter ms-2" href="<%= @event.chosen_date.outlook_url %>"><strong>Outlook Calendar</strong>
    <span><%= image_tag "outlook.png", height: 20, width: 20, class: "img-fluid" %></span></a>
  </div>
</div>

app/views/chosen_dates/show.html.erb
<div class="wrapper position-relative">
  <div class="container min-vh-100 d-flex flex-column justify-content-center align-items-center ">
    <div class="p-3 m-2 h1 position-absolute top-0 start-0">
      <%= link_to event_path(@event) do %>
        <i class="fas fa-arrow-left"></i>
      <% end %>
    </div>
    <%= render "modal", event: @event %>
  </div>
</div>